apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: locust-worker
  namespace: locust
  labels:
    name: locust-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: luqmansen/gosty-loadtest:latest
          imagePullPolicy: Always

          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              value: locust-master
            - name: TARGET_HOST
              value: "http://gosty-apiserver-loadtest.gosty.svc.cluster.local/"

      nodeSelector:
        locust: "true"

      tolerations:
        - key: "locust"
          operator: "Exists"
          effect: "NoSchedule"