apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: locust-master
  namespace: locust
  labels:
    name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - name: locust-master
          image: luqmansen/gosty-loadtest:latest
          imagePullPolicy: Always

          env:
            - name: LOCUST_MODE
              value: master
            - name: TARGET_HOST
              value: "http://34.101.215.90/"
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
