apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: locust-worker
  namespace: locust
  labels:
    name: locust-worker
spec:
  replicas: 4
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: luqmansen/gosty-loadtest:latest
          imagePullPolicy: Always

          resources:
            requests:
              cpu: "120m"
              memory: "128Mi"
            limits:
              cpu: "512m"
              memory: "512Mi"

          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              value: locust-master
            - name: TARGET_HOST
              value: "http://34.101.215.90/"
